spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-dry-glitter-aorqrbej-pooler.c-2.ap-southeast-1.aws.neon.tech/studyplanner?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_d3alTXKRj6vJ}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:Y29tcGxleF9zZWNyZXRfa2V5X2Zvcl9qd3RfYXV0aGVudGljYXRpb25fMjU2X2JpdHM=}
jwt.expiration=${JWT_EXPIRATION:86400000}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*,https://*.vercel.app}